app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s
base-urls:
  git-hub-api: https://api.github.com/
  stack-overflow-api: https://api.stackexchange.com/

spring:
  application:
    name: scrapper

spring-doc:
  api-docs:
    path: /v3/api-docs  # Путь к JSON спецификации
  swagger-ui:
    path: /swagger-ui.html  # Путь к странице Swagger UI

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
