app:
  database-access-type: jpa
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s
    link-checking-frequency: 2m
  retry-config:
    backoff: constant
    attempts: 3
    timeout: 5
# kafka
  useQueue: true
  bootstrap-server: localhost:9092
  topic: link-topic

base-urls:
  git-hub-api: https://api.github.com/
  stack-overflow-api: https://api.stackexchange.com/

spring:
  kafka:
    bootstrap-servers: localhost:9092
  application:
    name: scrapper
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: false
spring-doc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,info
      path-mapping:
        prometheus: metrics
      base-path: /
  metrics:
    tags:
      application: ${spring.application.name}
  server:
    port: 7070
server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
rate:
  limit: 10
time:
  duration:
    in:
      minutes: 1
