app:
  database-access-type: jpa
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s
    link-checking-frequency: 2m

base-urls:
  git-hub-api: https://api.github.com/
  stack-overflow-api: https://api.stackexchange.com/

spring:
  application:
    name: scrapper
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: false
spring-doc:
  api-docs:
    path: /v3/api-docs  # Путь к JSON спецификации
  swagger-ui:
    path: /swagger-ui.html  # Путь к странице Swagger UI

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
