app:
  telegram-token: ${TOKEN}
  scrapper-topic: link-topic
  bootstrap-servers: localhost:9092
spring:
  application:
    name: bot
  jackson:
    time-zone: UTC
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: links
server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,info
      path-mapping:
        prometheus: metrics
      base-path: /
  metrics:
    tags:
      application: ${spring.application.name}
  server:
    port: 7080
