app:
  telegram-token: ${TOKEN}
  scrapper-topic: link-topic
  bootstrap-servers: localhost:9092
spring:
  application:
    name: bot
  jackson:
    time-zone: UTC
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: links
server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml
