/*
 * This file is generated by jOOQ.
 */

package edu.java.scrapper.domain.jooq.tables.pojos;

import jakarta.validation.constraints.Size;
import java.beans.ConstructorProperties;
import java.io.Serializable;
import java.time.OffsetDateTime;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Links implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String url;
    private String description;
    private OffsetDateTime updatedAt;
    private OffsetDateTime lastChecked;
    private Integer openIssues;
    private Integer answerCount;

    public Links() {
    }

    public Links(Links value) {
        this.id = value.id;
        this.url = value.url;
        this.description = value.description;
        this.updatedAt = value.updatedAt;
        this.lastChecked = value.lastChecked;
        this.openIssues = value.openIssues;
        this.answerCount = value.answerCount;
    }

    @ConstructorProperties({"id", "url", "description", "updatedAt", "lastChecked", "openIssues", "answerCount"})
    public Links(
        @Nullable Long id,
        @NotNull String url,
        @Nullable String description,
        @Nullable OffsetDateTime updatedAt,
        @Nullable OffsetDateTime lastChecked,
        @Nullable Integer openIssues,
        @Nullable Integer answerCount
    ) {
        this.id = id;
        this.url = url;
        this.description = description;
        this.updatedAt = updatedAt;
        this.lastChecked = lastChecked;
        this.openIssues = openIssues;
        this.answerCount = answerCount;
    }

    /**
     * Getter for <code>LINKS.ID</code>.
     */
    @Nullable
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>LINKS.ID</code>.
     */
    public void setId(@Nullable Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>LINKS.URL</code>.
     */
    @jakarta.validation.constraints.NotNull
    @Size(max = 1000000000)
    @NotNull
    public String getUrl() {
        return this.url;
    }

    /**
     * Setter for <code>LINKS.URL</code>.
     */
    public void setUrl(@NotNull String url) {
        this.url = url;
    }

    /**
     * Getter for <code>LINKS.DESCRIPTION</code>.
     */
    @Size(max = 1000000000)
    @Nullable
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>LINKS.DESCRIPTION</code>.
     */
    public void setDescription(@Nullable String description) {
        this.description = description;
    }

    /**
     * Getter for <code>LINKS.UPDATED_AT</code>.
     */
    @Nullable
    public OffsetDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>LINKS.UPDATED_AT</code>.
     */
    public void setUpdatedAt(@Nullable OffsetDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>LINKS.LAST_CHECKED</code>.
     */
    @Nullable
    public OffsetDateTime getLastChecked() {
        return this.lastChecked;
    }

    /**
     * Setter for <code>LINKS.LAST_CHECKED</code>.
     */
    public void setLastChecked(@Nullable OffsetDateTime lastChecked) {
        this.lastChecked = lastChecked;
    }

    /**
     * Getter for <code>LINKS.OPEN_ISSUES</code>.
     */
    @Nullable
    public Integer getOpenIssues() {
        return this.openIssues;
    }

    /**
     * Setter for <code>LINKS.OPEN_ISSUES</code>.
     */
    public void setOpenIssues(@Nullable Integer openIssues) {
        this.openIssues = openIssues;
    }

    /**
     * Getter for <code>LINKS.ANSWER_COUNT</code>.
     */
    @Nullable
    public Integer getAnswerCount() {
        return this.answerCount;
    }

    /**
     * Setter for <code>LINKS.ANSWER_COUNT</code>.
     */
    public void setAnswerCount(@Nullable Integer answerCount) {
        this.answerCount = answerCount;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Links other = (Links) obj;
        if (this.id == null) {
            if (other.id != null) {
                return false;
            }
        } else if (!this.id.equals(other.id)) {
            return false;
        }
        if (this.url == null) {
            if (other.url != null) {
                return false;
            }
        } else if (!this.url.equals(other.url)) {
            return false;
        }
        if (this.description == null) {
            if (other.description != null) {
                return false;
            }
        } else if (!this.description.equals(other.description)) {
            return false;
        }
        if (this.updatedAt == null) {
            if (other.updatedAt != null) {
                return false;
            }
        } else if (!this.updatedAt.equals(other.updatedAt)) {
            return false;
        }
        if (this.lastChecked == null) {
            if (other.lastChecked != null) {
                return false;
            }
        } else if (!this.lastChecked.equals(other.lastChecked)) {
            return false;
        }
        if (this.openIssues == null) {
            if (other.openIssues != null) {
                return false;
            }
        } else if (!this.openIssues.equals(other.openIssues)) {
            return false;
        }
        if (this.answerCount == null) {
            if (other.answerCount != null) {
                return false;
            }
        } else if (!this.answerCount.equals(other.answerCount)) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.url == null) ? 0 : this.url.hashCode());
        result = prime * result + ((this.description == null) ? 0 : this.description.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        result = prime * result + ((this.lastChecked == null) ? 0 : this.lastChecked.hashCode());
        result = prime * result + ((this.openIssues == null) ? 0 : this.openIssues.hashCode());
        result = prime * result + ((this.answerCount == null) ? 0 : this.answerCount.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Links (");

        sb.append(id);
        sb.append(", ").append(url);
        sb.append(", ").append(description);
        sb.append(", ").append(updatedAt);
        sb.append(", ").append(lastChecked);
        sb.append(", ").append(openIssues);
        sb.append(", ").append(answerCount);

        sb.append(")");
        return sb.toString();
    }
}
